/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/4Runner.glb 
*/

import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function Runner4(props) {
  const { nodes, materials } = useGLTF('models/4Runner.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_20.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Tail_Lights} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Mirrors} />
      <mesh geometry={nodes.Body.geometry}>
        <meshStandardMaterial {...materials.BaseMtl} color={overlay==1 || overlay==13 ? (snap1.base.BaseMtl!=="none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
          <canvasTexture
            flipY={false}
            wrapS={1000}
            wrapT={1000}
            colorSpace='srgb'
            ref={textureRef}
            attach="map"
            image={canvasRef.current}
          />
        </meshStandardMaterial>
      </mesh>
      <mesh geometry={nodes.Object_10.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Indicators} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Tyres} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Rims} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.Rims} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.Hub_Lock} />
    </group>
  )
}

useGLTF.preload('/4Runner.glb')
